const VehilePartData = [
  {
    id: 1,
    marka: "MICHELIN",
    model: "A005EVO",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim:
      "https://medias89k.azureedge.net/sys-master-hybris-image-prod/h96/ha7/8797048963102?w=300&h=250&crop=true",
  },
  {
    id: 2,
    marka: "Michelin",
    model: "Pilot Sport 5",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim:
      "https://cxf-prod.azureedge.net/b2c-experience-production/attachments/ckvvz0m0z08x901kdi61j8ftr-4w-986-3528709222846-tire-michelin-pilot-sport-5-225-slash-40-zr18-92y-xl-sprite.png",
  },
  {
    id: 3,
    marka: "Michelin",
    model: "Primacy 4",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim:
      "https://medias89k.azureedge.net/sys-master-hybris-image-prod/h96/ha7/8797048963102?w=300&h=250&crop=true",
  },
  {
    id: 4,
    marka: "Michelin",
    model: "Pilot Sport 4",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim:
      "https://medias89k.azureedge.net/sys-master-hybris-image-prod/h96/ha7/8797048963102?w=300&h=250&crop=true",
  },
  {
    id: 5,
    marka: "Michelin",
    model: "Pilot Sport Cup 2",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[4](https://www.michelin.com.tr/)",
  },
  {
    id: 6,
    marka: "Michelin",
    model: "Pilot Sport EV",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[5](https://www.michelin.com.tr/)",
  },
  {
    id: 7,
    marka: "Michelin",
    model: "Energy Saver +",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[6](https://www.michelin.com.tr/)",
  },
  {
    id: 8,
    marka: "Michelin",
    model: "Pilot Super Sport",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[7](https://www.michelin.com.tr/)",
  },
  {
    id: 9,
    marka: "Michelin",
    model: "Pilot Sport 4 S",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[8](https://www.michelin.com.tr/)",
  },
  {
    id: 10,
    marka: "Michelin",
    model: "Pilot Sport Cup 2 R",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[9](https://www.michelin.com.tr/)",
  },
  {
    id: 11,
    marka: "Michelin",
    model: "Pilot Sport Cup 2 Connect",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[10](https://www.michelin.com.tr/)",
  },
  {
    id: 12,
    marka: "Michelin",
    model: "Primacy 3",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[11](https://www.michelin.com.tr/)",
  },
  {
    id: 13,
    marka: "Michelin",
    model: "Latitude Sport 3",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[12](https://www.michelin.com.tr/)",
  },
  {
    id: 14,
    marka: "Michelin",
    model: "Pilot Sport 3",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[13](https://www.michelin.com.tr/)",
  },
  {
    id: 15,
    marka: "Michelin",
    model: "Pilot Sport 4 SUV",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[14](https://www.michelin.com.tr/)",
  },
  {
    id: 16,
    marka: "Michelin",
    model: "Agilis 3",
    aractipi: "otomobil",
    ozelligi: "yaz lastiği",
    resim: "[15](https://www.michelin.com.tr/)",
  },
];
export default VehilePartData;
